[tool.poetry]
name = "python-api-scraper"
version = "0.1.0"
description = ""
authors = ["Zahyr Seferina <zahyr.seferina@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
